
-- Safe staged runbook: split mdma_2cx_dox_nbome into mdma/two_c_x/dox/nbome_series
-- Generated from interactions-update.csv

create table if not exists public.interactions_split_stage (
  pair_key text primary key,
  substance_a_id text not null,
  substance_b_id text not null,
  is_self_pair boolean not null,
  classification_code text,
  classification_confidence text,
  risk_score numeric,
  risk_label text,
  headline text,
  mechanism_summary text,
  timing_guidance text,
  field_notes text,
  primary_mechanism_category text,
  mechanism_categories jsonb not null default '[]'::jsonb,
  evidence_gaps text,
  provenance_confidence_tier text,
  provenance_rationale text
);

truncate table public.interactions_split_stage;

insert into public.interactions_split_stage (
  pair_key, substance_a_id, substance_b_id, is_self_pair, classification_code,
  classification_confidence, risk_score, risk_label, headline, mechanism_summary,
  timing_guidance, field_notes, primary_mechanism_category, mechanism_categories,
  evidence_gaps, provenance_confidence_tier, provenance_rationale
)
values
('ayahuasca|mdma', 'ayahuasca', 'mdma', false, 'DANGEROUS', 'high', 5.0, 'Dangerous / Contraindicated', 'MDMA is contraindicated with ayahuasca.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, 'high', 'Directly loaded from source-cited interaction rows.'),
('ayahuasca|two_c_x', 'ayahuasca', 'two_c_x', false, 'DANGEROUS', 'high', 5.0, 'Dangerous / Contraindicated', '2C-x psychedelic phenethylamines are contraindicated with ayahuasca.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, 'high', 'Directly loaded from source-cited interaction rows.'),
('ayahuasca|dox', 'ayahuasca', 'dox', false, 'DANGEROUS', 'high', 5.0, 'Dangerous / Contraindicated', 'DOx psychedelic amphetamines are contraindicated with ayahuasca.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, 'high', 'Directly loaded from source-cited interaction rows.'),
('ayahuasca|nbome_series', 'ayahuasca', 'nbome_series', false, 'DANGEROUS', 'high', 5.0, 'Dangerous / Contraindicated', 'NBOMe compounds are contraindicated with ayahuasca.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, 'high', 'Directly loaded from source-cited interaction rows.'),
('mdma|psilocybin', 'psilocybin', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('psilocybin|two_c_x', 'psilocybin', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|psilocybin', 'psilocybin', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|psilocybin', 'psilocybin', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|nn_dmt', 'nn_dmt', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nn_dmt|two_c_x', 'nn_dmt', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|nn_dmt', 'nn_dmt', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|nn_dmt', 'nn_dmt', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('five_meo_dmt|mdma', 'five_meo_dmt', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('five_meo_dmt|two_c_x', 'five_meo_dmt', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|five_meo_dmt', 'five_meo_dmt', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('five_meo_dmt|nbome_series', 'five_meo_dmt', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|mescaline_peyote', 'mescaline_peyote', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mescaline_peyote|two_c_x', 'mescaline_peyote', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|mescaline_peyote', 'mescaline_peyote', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mescaline_peyote|nbome_series', 'mescaline_peyote', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|yopo', 'yopo', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('two_c_x|yopo', 'yopo', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|yopo', 'yopo', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|yopo', 'yopo', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lsd|mdma', 'lsd', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lsd|two_c_x', 'lsd', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|lsd', 'lsd', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lsd|nbome_series', 'lsd', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|salvia', 'salvia', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('salvia|two_c_x', 'salvia', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|salvia', 'salvia', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|salvia', 'salvia', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('belladonna|mdma', 'belladonna', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('belladonna|two_c_x', 'belladonna', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('belladonna|dox', 'belladonna', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('belladonna|nbome_series', 'belladonna', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('brugmansia|mdma', 'brugmansia', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('brugmansia|two_c_x', 'brugmansia', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('brugmansia|dox', 'brugmansia', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('brugmansia|nbome_series', 'brugmansia', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('kambo|mdma', 'kambo', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('kambo|two_c_x', 'kambo', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|kambo', 'kambo', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('kambo|nbome_series', 'kambo', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|tobacco_rape', 'tobacco_rape', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('tobacco_rape|two_c_x', 'tobacco_rape', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|tobacco_rape', 'tobacco_rape', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|tobacco_rape', 'tobacco_rape', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cannabis|mdma', 'cannabis', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cannabis|two_c_x', 'cannabis', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cannabis|dox', 'cannabis', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cannabis|nbome_series', 'cannabis', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('alcohol|mdma', 'alcohol', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('alcohol|two_c_x', 'alcohol', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('alcohol|dox', 'alcohol', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('alcohol|nbome_series', 'alcohol', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|ssri', 'ssri', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('ssri|two_c_x', 'ssri', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|ssri', 'ssri', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|ssri', 'ssri', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|snri', 'snri', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('snri|two_c_x', 'snri', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|snri', 'snri', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|snri', 'snri', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|tricyclic_ad', 'tricyclic_ad', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('tricyclic_ad|two_c_x', 'tricyclic_ad', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|tricyclic_ad', 'tricyclic_ad', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|tricyclic_ad', 'tricyclic_ad', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('maoi_pharma|mdma', 'maoi_pharma', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('maoi_pharma|two_c_x', 'maoi_pharma', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|maoi_pharma', 'maoi_pharma', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('maoi_pharma|nbome_series', 'maoi_pharma', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('atypical_ad|mdma', 'atypical_ad', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('atypical_ad|two_c_x', 'atypical_ad', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('atypical_ad|dox', 'atypical_ad', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('atypical_ad|nbome_series', 'atypical_ad', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|ndri_bupropion', 'ndri_bupropion', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('ndri_bupropion|two_c_x', 'ndri_bupropion', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|ndri_bupropion', 'ndri_bupropion', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|ndri_bupropion', 'ndri_bupropion', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('amphetamine_stims|mdma', 'amphetamine_stims', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('amphetamine_stims|two_c_x', 'amphetamine_stims', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('amphetamine_stims|dox', 'amphetamine_stims', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('amphetamine_stims|nbome_series', 'amphetamine_stims', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|methylphenidate', 'methylphenidate', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('methylphenidate|two_c_x', 'methylphenidate', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|methylphenidate', 'methylphenidate', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('methylphenidate|nbome_series', 'methylphenidate', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cocaine|mdma', 'cocaine', 'mdma', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cocaine|two_c_x', 'cocaine', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cocaine|dox', 'cocaine', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('cocaine|nbome_series', 'cocaine', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|mdma', 'mdma', 'mdma', true, 'SELF', 'not_applicable', -1, 'Same Entity / N-A', 'Same entity selected; this is not an interaction pair.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, NULL, 'Self-pair identity row for the same substance selected twice.'),
('mdma|two_c_x', 'mdma', 'two_c_x', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|mdma', 'mdma', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|nbome_series', 'mdma', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('mdma|serotonergic_opioids', 'mdma', 'serotonergic_opioids', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antipsychotics|mdma', 'mdma', 'antipsychotics', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antihypertensives|mdma', 'mdma', 'antihypertensives', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('benzodiazepines|mdma', 'mdma', 'benzodiazepines', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lithium|mdma', 'mdma', 'lithium', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lamotrigine|mdma', 'mdma', 'lamotrigine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('ketamine|mdma', 'mdma', 'ketamine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('clonidine_guanfacine|mdma', 'mdma', 'clonidine_guanfacine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('beta_blockers_ccb|mdma', 'mdma', 'beta_blockers_ccb', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('two_c_x|two_c_x', 'two_c_x', 'two_c_x', true, 'SELF', 'not_applicable', -1, 'Same Entity / N-A', 'Same entity selected; this is not an interaction pair.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, NULL, 'Self-pair identity row for the same substance selected twice.'),
('dox|two_c_x', 'two_c_x', 'dox', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|two_c_x', 'two_c_x', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('serotonergic_opioids|two_c_x', 'two_c_x', 'serotonergic_opioids', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antipsychotics|two_c_x', 'two_c_x', 'antipsychotics', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antihypertensives|two_c_x', 'two_c_x', 'antihypertensives', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('benzodiazepines|two_c_x', 'two_c_x', 'benzodiazepines', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lithium|two_c_x', 'two_c_x', 'lithium', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lamotrigine|two_c_x', 'two_c_x', 'lamotrigine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('ketamine|two_c_x', 'two_c_x', 'ketamine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('clonidine_guanfacine|two_c_x', 'two_c_x', 'clonidine_guanfacine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('beta_blockers_ccb|two_c_x', 'two_c_x', 'beta_blockers_ccb', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|dox', 'dox', 'dox', true, 'SELF', 'not_applicable', -1, 'Same Entity / N-A', 'Same entity selected; this is not an interaction pair.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, NULL, 'Self-pair identity row for the same substance selected twice.'),
('dox|nbome_series', 'dox', 'nbome_series', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|serotonergic_opioids', 'dox', 'serotonergic_opioids', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antipsychotics|dox', 'dox', 'antipsychotics', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antihypertensives|dox', 'dox', 'antihypertensives', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('benzodiazepines|dox', 'dox', 'benzodiazepines', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|lithium', 'dox', 'lithium', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|lamotrigine', 'dox', 'lamotrigine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('dox|ketamine', 'dox', 'ketamine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('clonidine_guanfacine|dox', 'dox', 'clonidine_guanfacine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('beta_blockers_ccb|dox', 'dox', 'beta_blockers_ccb', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('nbome_series|nbome_series', 'nbome_series', 'nbome_series', true, 'SELF', 'not_applicable', -1, 'Same Entity / N-A', 'Same entity selected; this is not an interaction pair.', NULL, NULL, NULL, 'unknown', '[]'::jsonb, NULL, NULL, 'Self-pair identity row for the same substance selected twice.'),
('nbome_series|serotonergic_opioids', 'nbome_series', 'serotonergic_opioids', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antipsychotics|nbome_series', 'nbome_series', 'antipsychotics', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('antihypertensives|nbome_series', 'nbome_series', 'antihypertensives', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('benzodiazepines|nbome_series', 'nbome_series', 'benzodiazepines', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lithium|nbome_series', 'nbome_series', 'lithium', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('lamotrigine|nbome_series', 'nbome_series', 'lamotrigine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('ketamine|nbome_series', 'nbome_series', 'ketamine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('clonidine_guanfacine|nbome_series', 'nbome_series', 'clonidine_guanfacine', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.'),
('beta_blockers_ccb|nbome_series', 'nbome_series', 'beta_blockers_ccb', false, 'INFERRED', 'low', NULL, 'Unknown/Insufficient Data', 'No explicit interaction classification is loaded for this pair in the current curated dataset.', NULL, NULL, NULL, 'psychiatric_destabilization', '[]'::jsonb, NULL, 'low', 'No explicit rule is loaded for this pair in the current dataset.');

-- Preflight counts before transaction
select 'stage_rows' as metric, count(*)::int as value from public.interactions_split_stage;
select 'stage_distinct_pairs' as metric, count(distinct pair_key)::int as value from public.interactions_split_stage;
select 'legacy_aggregate_pairs' as metric, count(*)::int as value from public.interactions where substance_a_id='mdma_2cx_dox_nbome' or substance_b_id='mdma_2cx_dox_nbome';

begin;

create table public.substances_backup_mdma_split_20260501_134230 as
select * from public.substances where id in ('mdma_2cx_dox_nbome','mdma','two_c_x','dox','nbome_series');

create table public.interactions_backup_mdma_split_20260501_134230 as
select * from public.interactions where substance_a_id='mdma_2cx_dox_nbome' or substance_b_id='mdma_2cx_dox_nbome' or substance_a_id in ('mdma','two_c_x','dox','nbome_series') or substance_b_id in ('mdma','two_c_x','dox','nbome_series');

insert into public.substances (
  id, name, class, mechanism_tag, notes, deprecated, superseded_by, source_schema_version, source_generated_at
)
values
('mdma', 'MDMA', 'Recreational Serotonergic', 'Serotonergic entactogen', 'Split from legacy aggregate node mdma_2cx_dox_nbome.', false, NULL, 'v2', now()),
('two_c_x', '2C-x', 'Recreational Serotonergic', 'Phenethylamine psychedelic series', 'Split from legacy aggregate node mdma_2cx_dox_nbome.', false, NULL, 'v2', now()),
('dox', 'DOx', 'Recreational Serotonergic', 'Psychedelic amphetamine series', 'Split from legacy aggregate node mdma_2cx_dox_nbome.', false, NULL, 'v2', now()),
('nbome_series', 'NBOMe Series', 'Recreational Serotonergic', 'NBOMe phenethylamine series', 'Split from legacy aggregate node mdma_2cx_dox_nbome.', false, NULL, 'v2', now())
on conflict (id) do update set
  name = excluded.name,
  class = excluded.class,
  mechanism_tag = excluded.mechanism_tag,
  notes = excluded.notes,
  source_schema_version = excluded.source_schema_version,
  source_generated_at = excluded.source_generated_at;

insert into public.interactions (
  pair_key, substance_a_id, substance_b_id, is_self_pair, classification_code,
  classification_confidence, risk_score, risk_label, headline, mechanism_summary,
  timing_guidance, field_notes, primary_mechanism_category, mechanism_categories,
  evidence_gaps, provenance_confidence_tier, provenance_rationale
)
select
  pair_key, substance_a_id, substance_b_id, is_self_pair, classification_code,
  classification_confidence, risk_score, risk_label, headline, mechanism_summary,
  timing_guidance, field_notes, primary_mechanism_category, mechanism_categories,
  evidence_gaps, provenance_confidence_tier, provenance_rationale
from public.interactions_split_stage
on conflict (pair_key) do update set
  substance_a_id = excluded.substance_a_id,
  substance_b_id = excluded.substance_b_id,
  is_self_pair = excluded.is_self_pair,
  classification_code = excluded.classification_code,
  classification_confidence = excluded.classification_confidence,
  risk_score = excluded.risk_score,
  risk_label = excluded.risk_label,
  headline = excluded.headline,
  mechanism_summary = excluded.mechanism_summary,
  timing_guidance = excluded.timing_guidance,
  field_notes = excluded.field_notes,
  primary_mechanism_category = excluded.primary_mechanism_category,
  mechanism_categories = excluded.mechanism_categories,
  evidence_gaps = excluded.evidence_gaps,
  provenance_confidence_tier = excluded.provenance_confidence_tier,
  provenance_rationale = excluded.provenance_rationale;

delete from public.interactions
where substance_a_id='mdma_2cx_dox_nbome' or substance_b_id='mdma_2cx_dox_nbome';

update public.substances
set
  deprecated = true,
  superseded_by = 'mdma',
  notes = coalesce(notes, '') || case when coalesce(notes,'') = '' then '' else ' ' end || 'Deprecated after entactogen split into mdma, two_c_x, dox, nbome_series.',
  source_schema_version = 'v2',
  source_generated_at = now()
where id = 'mdma_2cx_dox_nbome';

commit;

-- Post-run validations
select 'substances_total' as metric, count(*)::int as value from public.substances
union all select 'interactions_total', count(*)::int from public.interactions
union all select 'aggregate_pairs_remaining', count(*)::int from public.interactions where substance_a_id='mdma_2cx_dox_nbome' or substance_b_id='mdma_2cx_dox_nbome'
union all select 'new_split_pairs', count(*)::int from public.interactions where substance_a_id in ('mdma','two_c_x','dox','nbome_series') or substance_b_id in ('mdma','two_c_x','dox','nbome_series')
union all select 'new_split_self_pairs', count(*)::int from public.interactions where is_self_pair and substance_a_id in ('mdma','two_c_x','dox','nbome_series')
union all select 'pair_key_mismatch', count(*)::int from public.interactions where pair_key <> (least(substance_a_id, substance_b_id) || '|' || greatest(substance_a_id, substance_b_id))
union all select 'self_flag_mismatch', count(*)::int from public.interactions where is_self_pair <> (substance_a_id = substance_b_id)
union all select 'non_array_mechanism_categories', count(*)::int from public.interactions where jsonb_typeof(mechanism_categories) is distinct from 'array';

select id, name, deprecated, superseded_by from public.substances where id in ('mdma_2cx_dox_nbome','mdma','two_c_x','dox','nbome_series') order by id;
